name: build
on:
  push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      checks: write

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'
          cache: true

      - name: Restore workloads
        run: dotnet workload restore

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: |
          for testProject in System/src/*.*Tests.csproj; do
            testFileName=$(basename "$testProject" .csproj)
            dotnet test "$testProject" --no-restore --logger:"junit;LogFilePath=$PWD/Results/$testFileName.xml" || true
          done

      - name: Publish Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Test Results
          path: '**/Results/*.xml'

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test Report
          path: "**/Results/*.xml"
          reporter: java-junit
          fail-on-error: true

      - name: Test Summary
        uses: test-summary/action@v2
        if: always()
        with:
          paths: "**/Results/*.xml"